### ISSUE TITLE
🔧 App Rework

### ISSUE THREAD

**Issue by fedetomassini** [fedetomassini/vaultify#23]
## Tasks
- [x] Review the existing code structure.
- [x] Refactor components to improve readability and maintainability.
- [x] Redesign the UI for better usability and responsiveness.
- [x] Open source project.
